{
 "title": "Humidity",
 "description": "Visualise power metrics coming from Humidity-Control",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Fan ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.SW.Fan",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Trigger",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.SW.Temp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hysteresis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.SW.Hum",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Delta Humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.SW.Delta",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature (Outdoor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.FAussen.Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity (Outdoor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.FAussen.Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature (Indoor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.FInnen.Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity (Indoor)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.FInnen.Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Temperatur",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Outdoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.FAussen.Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Indoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.FInnen.Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity (relative)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "alias": "Outdoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.FAussen.Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Indoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.FInnen.Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity (absolute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "congm3" } },
   "targets": [
    {
     "alias": "Outdoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.AFeuchte.Aussen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Indoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.AFeuchte.Innen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Dew point",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Outdoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.AFeuchte.TPA",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Indoor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "mqtt.0.ESPEasy.AFeuchte.TPI",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}